language: java
jdk:
  - oraclejdk17

before_install:
  - sudo apt-get update
  - cd app/
  - echo "Let's start Maven Package"
  - mvn package
  - cd ..
  - echo "We are in the Docker folder!"


script:
  - docker-compose build

before_deploy:
  echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script:
    docker tag projectcedro:latest luisfeliperodrigues/projectcedro-deploy:latest;
    docker push luisfeliperodrigues/projectcedro-deploy:latest;
  on:
    branch: main

notifications:
  email:
    recipients:
      - luisfelipebr1995@gmail.com
    on_success: always # Notificar em caso de sucesso
    on_failure: always # Notificar em caso de falha