version: "3.4"
services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: 99620530159aA
      MYSQL_USER: admin
      MYSQL_PASSWORD: 99620530159aA
      MYSQL_DATABASE: labcedro
    ports:
      - "3308:3306"
    networks:
      - labcedro-network

  projectcedro:
    image: projectcedro
    restart: always
    build:
      context: .
      dockerfile: app/Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - labcedro-network
networks:
    labcedro-network:
      driver: bridge
